import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Check, ChevronDown, FileText, HeartHandshake, Lightbulb, ShieldCheck, Sparkles } from "lucide-react"

export type ContentCard = { title: string; description: string; href?: string }

export function EditorialIntro({ eyebrow, title, description, image, alt }: { eyebrow: string; title: string; description: string; image?: string; alt?: string }) {
  return <section className="border-b border-foreground/10 px-6 py-16 md:px-12 md:py-24"><div className="mx-auto flex max-w-6xl flex-col gap-10 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-sm uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-6 text-balance text-4xl leading-[1.05] text-foreground md:text-6xl">{title}</h1><p className="mt-7 max-w-2xl text-pretty text-base leading-relaxed text-muted-foreground md:text-lg">{description}</p></div>{image && <div className="relative aspect-[4/3] w-full overflow-hidden rounded-3xl bg-muted lg:max-w-sm"><Image src={image} alt={alt ?? ""} fill className="object-cover" sizes="(min-width: 1024px) 30vw, 100vw" /></div>}</div></section>
}

export function StoryGrid({ eyebrow, title, items }: { eyebrow?: string; title: string; items: ContentCard[] }) {
  return <section className="px-6 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-6xl"><div className="max-w-2xl">{eyebrow && <p className="text-sm uppercase tracking-[0.18em] text-primary">{eyebrow}</p>}<h2 className="mt-4 text-balance text-2xl text-foreground md:text-4xl">{title}</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map((item, index) => { const content = <article className="flex h-full flex-col rounded-2xl bg-card p-6 ring-1 ring-foreground/10 transition-transform hover:-translate-y-1"><span className="font-mono text-xs text-primary">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-8 text-xl text-foreground">{item.title}</h3><p className="mt-3 flex-1 text-sm leading-relaxed text-muted-foreground">{item.description}</p>{item.href && <span className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-primary">Перейти<ArrowRight className="size-4" /></span>}</article>; return item.href ? <Link href={item.href} key={item.title}>{content}</Link> : <div key={item.title}>{content}</div> })}</div></div></section>
}

export function ProcessRail({ title, steps }: { title: string; steps: ContentCard[] }) { return <section className="bg-muted px-6 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-6xl"><h2 className="text-2xl text-foreground md:text-4xl">{title}</h2><div className="mt-10 grid gap-4 lg:grid-cols-4">{steps.map((step, index) => <article key={step.title} className="relative rounded-2xl bg-background p-6 ring-1 ring-foreground/10"><span className="flex size-9 items-center justify-center rounded-full bg-primary text-sm text-primary-foreground">{index + 1}</span><h3 className="mt-6 text-lg text-foreground">{step.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{step.description}</p></article>)}</div></div></section> }

export function ProofSection({ title, description, items, image, alt }: { title: string; description: string; items: string[]; image?: string; alt?: string }) { return <section className="bg-secondary px-6 py-16 text-secondary-foreground md:px-12 md:py-24"><div className="mx-auto flex max-w-6xl flex-col gap-10 lg:flex-row lg:items-center">{image && <div className="relative aspect-[4/3] overflow-hidden rounded-3xl lg:w-1/2"><Image src={image} alt={alt ?? ""} fill className="object-cover" sizes="(min-width: 1024px) 50vw, 100vw" /></div>}<div className="max-w-xl"><ShieldCheck className="size-9 text-primary-foreground" /><h2 className="mt-6 text-2xl md:text-4xl">{title}</h2><p className="mt-5 text-sm leading-relaxed text-secondary-foreground/70 md:text-base">{description}</p><ul className="mt-8 flex flex-col gap-4">{items.map(item => <li key={item} className="flex gap-3 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-primary-foreground" />{item}</li>)}</ul></div></div></section> }

export function FaqList({ items }: { items: { question: string; answer: string }[] }) { return <section className="px-6 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-4xl"><div className="flex items-center gap-3"><Sparkles className="size-6 text-primary" /><p className="text-sm uppercase tracking-[0.18em] text-primary">Поширені запитання</p></div><div className="mt-8 flex flex-col divide-y divide-foreground/10">{items.map(item => <details key={item.question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg text-foreground"><span>{item.question}</span><ChevronDown className="size-5 shrink-0 text-primary transition-transform group-open:rotate-180" /></summary><p className="max-w-3xl pt-4 text-sm leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></div></section> }

export function ActionBand({ title, description, actions }: { title: string; description: string; actions: { label: string; href: string }[] }) { return <section className="px-6 py-16 md:px-12 md:py-24"><div className="mx-auto flex max-w-6xl flex-col gap-8 rounded-3xl bg-primary p-8 text-primary-foreground md:p-12 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><HeartHandshake className="size-9" /><h2 className="mt-6 text-2xl md:text-4xl">{title}</h2><p className="mt-5 text-sm leading-relaxed text-primary-foreground/75 md:text-base">{description}</p></div><div className="flex flex-wrap gap-3">{actions.map(action => <Link key={action.href} href={action.href} className="inline-flex items-center gap-2 rounded-full bg-card px-5 py-3 text-sm text-card-foreground transition-colors hover:bg-muted">{action.label}<ArrowRight className="size-4" /></Link>)}</div></div></section> }

export function DocumentIntro({ title, description, updated }: { title: string; description: string; updated: string }) { return <section className="border-b border-foreground/10 px-6 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-4xl"><FileText className="size-9 text-primary" /><h1 className="mt-6 text-balance text-4xl text-foreground md:text-6xl">{title}</h1><p className="mt-6 text-base leading-relaxed text-muted-foreground">{description}</p><p className="mt-5 font-mono text-xs uppercase tracking-[0.16em] text-primary">Оновлено: {updated}</p></div></section> }

export function DocumentSections({ sections }: { sections: { title: string; text: string }[] }) { return <section className="px-6 py-16 md:px-12 md:py-24"><div className="mx-auto flex max-w-4xl flex-col gap-10">{sections.map(section => <article key={section.title}><h2 className="text-xl text-foreground md:text-2xl">{section.title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground md:text-base">{section.text}</p></article>)}</div></section> }

export const icons = { lightbulb: <Lightbulb className="size-6" />, handshake: <HeartHandshake className="size-6" /> }
