import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Check, CircleDot, HeartHandshake, Quote, ShieldCheck, Sparkles } from "lucide-react"

export type UniquePageConfig = {
  eyebrow: string
  title: string
  intro: string
  image?: string
  imageAlt?: string
  sections: { eyebrow: string; title: string; text: string; bullets?: string[]; image?: string; imageAlt?: string; href?: string; linkLabel?: string }[]
  quote?: string
  actions: { label: string; href: string }[]
}

export function UniquePublicPage({ config }: { config: UniquePageConfig }) {
  return <main className="min-h-screen">
    <section className="border-b border-foreground/10 px-6 py-16 md:px-12 md:py-24"><div className="mx-auto flex max-w-6xl flex-col gap-10 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-sm uppercase tracking-[0.18em] text-primary">{config.eyebrow}</p><h1 className="mt-6 text-balance text-4xl leading-[1.05] text-foreground md:text-6xl">{config.title}</h1><p className="mt-7 max-w-2xl text-pretty text-base leading-relaxed text-muted-foreground md:text-lg">{config.intro}</p></div>{config.image && <div className="relative aspect-[4/3] w-full overflow-hidden rounded-3xl bg-muted lg:max-w-sm"><Image src={config.image} alt={config.imageAlt ?? ""} fill className="object-cover" sizes="(min-width: 1024px) 30vw, 100vw" /></div>}</div></section>
    {config.sections.map((section, index) => <section key={section.title} className={`px-6 py-16 md:px-12 md:py-24 ${index % 2 === 1 ? "bg-muted" : ""}`}><div className={`mx-auto flex max-w-6xl flex-col gap-10 lg:flex-row lg:items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>{section.image && <div className="relative aspect-[4/3] overflow-hidden rounded-3xl lg:w-5/12"><Image src={section.image} alt={section.imageAlt ?? ""} fill className="object-cover" sizes="(min-width: 1024px) 42vw, 100vw" /></div>}<div className="max-w-2xl lg:flex-1"><p className="text-sm uppercase tracking-[0.18em] text-primary">{section.eyebrow}</p><h2 className="mt-4 text-balance text-2xl leading-tight text-foreground md:text-4xl">{section.title}</h2><p className="mt-5 text-pretty text-sm leading-relaxed text-muted-foreground md:text-base">{section.text}</p>{section.bullets && <ul className="mt-7 grid gap-3 sm:grid-cols-2">{section.bullets.map((bullet) => <li key={bullet} className="flex gap-3 text-sm leading-relaxed text-foreground"><Check className="mt-0.5 size-4 shrink-0 text-primary" />{bullet}</li>)}</ul>}{section.href && <Link href={section.href} className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline">{section.linkLabel ?? "Дізнатися більше"}<ArrowRight className="size-4" /></Link>}</div></div></section>)}
    {config.quote && <section className="bg-secondary px-6 py-16 text-secondary-foreground md:px-12 md:py-24"><div className="mx-auto max-w-4xl text-center"><Quote className="mx-auto size-9 text-primary-foreground" /><blockquote className="mt-6 text-balance text-2xl leading-tight md:text-4xl">{config.quote}</blockquote></div></section>}
    <section className="px-6 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-6xl rounded-3xl bg-primary p-8 text-primary-foreground md:p-12"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><HeartHandshake className="size-9" /><h2 className="mt-5 text-2xl md:text-4xl">Наступний крок може початися тут</h2><p className="mt-4 text-sm leading-relaxed text-primary-foreground/75">Оберіть шлях, який відповідає вашій ситуації, або напишіть нам — ми допоможемо знайти правильну точку входу.</p></div><div className="flex flex-wrap gap-3">{config.actions.map((action) => <Link key={action.href} href={action.href} className="inline-flex items-center gap-2 rounded-full bg-card px-5 py-3 text-sm text-card-foreground hover:bg-muted">{action.label}<ArrowRight className="size-4" /></Link>)}</div></div></div></section>
  </main>
}

export function PublicRouteMap({ title, intro, links }: { title: string; intro: string; links: { label: string; href: string; description: string }[] }) { return <section className="border-b border-foreground/10 px-6 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-sm uppercase tracking-[0.18em] text-primary">Навігація INPOM</p><h1 className="mt-5 text-balance text-4xl text-foreground md:text-6xl">{title}</h1><p className="mt-6 text-base leading-relaxed text-muted-foreground">{intro}</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{links.map((link) => <Link key={link.href} href={link.href} className="group rounded-2xl bg-card p-6 ring-1 ring-foreground/10 transition-transform hover:-translate-y-1"><div className="flex items-center justify-between"><CircleDot className="size-6 text-primary" /><ArrowRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div><h2 className="mt-8 text-xl text-foreground">{link.label}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{link.description}</p></Link>)}</div></div></section> }

export function DocumentRoute({ title, intro, sections }: { title: string; intro: string; sections: { title: string; text: string }[] }) { return <main className="min-h-screen"><section className="border-b border-foreground/10 px-6 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-4xl"><ShieldCheck className="size-9 text-primary" /><h1 className="mt-6 text-balance text-4xl text-foreground md:text-6xl">{title}</h1><p className="mt-6 text-base leading-relaxed text-muted-foreground">{intro}</p></div></section><section className="px-6 py-16 md:px-12 md:py-24"><div className="mx-auto grid max-w-5xl gap-5 md:grid-cols-2">{sections.map((section) => <article key={section.title} className="rounded-2xl bg-card p-6 ring-1 ring-foreground/10"><Sparkles className="size-6 text-primary" /><h2 className="mt-6 text-xl text-foreground">{section.title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{section.text}</p></article>)}</div></section></main> }

export const publicImages = { community: "/images/inpom-community.png", opportunity: "/images/inpom-opportunity.png", support: "/images/inpom-support.png", trust: "/images/inpom-trust.png", partnership: "/images/inpom-partnership.png", global: "/images/inpom-global.png" }
