"use client"

import { AnimatePresence, motion } from "framer-motion"
import { ArrowRight, Check, Clipboard, Copy, HeartHandshake, ShieldCheck } from "lucide-react"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"

const currencies = ["UAH", "EUR", "USD"] as const
const methods = [{ id: "iban", label: "IBAN", hint: "Банківський переказ" }, { id: "card", label: "Картка", hint: "Переказ на картку" }, { id: "crypto", label: "Crypto", hint: "Цифрові активи" }] as const

export function DonationFlow() {
  const router = useRouter()
  const [step, setStep] = useState<"start" | "details" | "sent">("start")
  const [amount, setAmount] = useState("100")
  const [currency, setCurrency] = useState<(typeof currencies)[number]>("UAH")
  const [methodType, setMethodType] = useState<(typeof methods)[number]["id"]>("iban")
  const [method, setMethod] = useState<any>(null)
  const [reference, setReference] = useState("")
  const [expiresAt, setExpiresAt] = useState("")
  const [error, setError] = useState("")
  const [copied, setCopied] = useState("")
  const [secondsLeft, setSecondsLeft] = useState(0)

  useEffect(() => {
    if (step !== "details" || !expiresAt) return
    const tick = () => setSecondsLeft(Math.max(0, Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000)))
    tick()
    const timer = window.setInterval(tick, 1000)
    return () => window.clearInterval(timer)
  }, [step, expiresAt])

  async function showDetails() { setError(""); const response = await fetch(`/api/donations?type=${methodType}&currency=${currency}`); const data = await response.json(); if (!response.ok) return setError(data.error); setMethod(data.method); setExpiresAt(data.expiresAt); setStep("details") }
  async function confirm() { setError(""); const response = await fetch("/api/donations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount, currency, methodType }) }); const data = await response.json(); if (!response.ok) return setError(data.error); setReference(data.reference); setExpiresAt(data.expiresAt); setStep("sent") }
  function copy(value: string, key: string) { navigator.clipboard?.writeText(value); setCopied(key); setTimeout(() => setCopied(""), 1600) }
  const detailText = method?.details || ""
  return <div className="mx-auto max-w-5xl px-4 pb-12 pt-20 sm:px-6">
    <AnimatePresence mode="wait">
      {step === "start" && <motion.section key="start" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -16 }} className="grid gap-5 lg:grid-cols-[1.1fr_.9fr] lg:items-center">
        <div><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-2 text-sm font-medium text-primary"><HeartHandshake className="size-4" /> Підтримка, що працює</div><h1 className="max-w-2xl text-balance text-3xl font-semibold tracking-tight sm:text-5xl">Ваша підтримка запускає нові можливості</h1><p className="mt-4 max-w-xl text-base leading-7 text-muted-foreground">Донат допомагає INPOM розвивати спільноту, менторські програми, проєкти та доступ жінок до міжнародних партнерств.</p><div className="mt-8 grid gap-3 text-sm text-muted-foreground sm:grid-cols-3"><span className="rounded-xl border border-foreground/10 bg-card p-4">Відкрито</span><span className="rounded-xl border border-foreground/10 bg-card p-4">Прозоро</span><span className="rounded-xl border border-foreground/10 bg-card p-4">Вручну перевіряється</span></div></div>
        <motion.div layout className="rounded-2xl border border-foreground/10 bg-card p-4 shadow-xl sm:p-5"><h2 className="text-xl font-semibold">Оберіть внесок</h2><p className="mt-2 text-sm text-muted-foreground">Після переказу адміністратор перевірить оплату вручну.</p><label className="mt-6 block text-sm font-medium">Сума</label><div className="mt-2 flex gap-2"><input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-foreground/15 bg-background px-4 py-3 text-lg outline-none ring-primary focus:ring-2" /><select value={currency} onChange={e => setCurrency(e.target.value as any)} className="rounded-xl border border-foreground/15 bg-background px-3 py-3 font-medium">{currencies.map(c => <option key={c}>{c}</option>)}</select></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{methods.map(item => <button type="button" key={item.id} onClick={() => setMethodType(item.id)} className={`rounded-xl border p-3 text-left transition ${methodType === item.id ? "border-primary bg-primary/10" : "border-foreground/10 hover:border-primary/40"}`}><span className="block font-semibold">{item.label}</span><span className="text-xs text-muted-foreground">{item.hint}</span></button>)}</div>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}<button type="button" onClick={showDetails} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 font-medium text-primary-foreground transition hover:opacity-90">Переглянути реквізити <ArrowRight className="size-4" /></button></motion.div>
      </motion.section>}
      {step === "details" && <motion.section key="details" initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -18 }} className="mx-auto max-w-2xl"><button type="button" onClick={() => setStep("start")} className="mb-6 text-sm text-muted-foreground hover:text-foreground">← Змінити спосіб</button><div className="rounded-2xl border border-foreground/10 bg-card p-4 shadow-xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Крок 2 · реквізити</p><h1 className="mt-1.5 text-2xl font-semibold">Зробіть переказ</h1></div><ShieldCheck className="size-7 text-primary" /></div><div className="mt-6 rounded-2xl bg-primary/10 p-4"><p className="text-sm text-muted-foreground">До переказу</p><p className="mt-1 text-xl font-semibold">{amount} {currency}</p></div><div className="mt-6 space-y-4">{[["Отримувач", method?.recipient_name], ["Реквізити", detailText]].map(([label, value]) => <div key={label} className="rounded-2xl border border-foreground/10 p-4"><div className="flex items-center justify-between gap-3"><span className="text-xs uppercase tracking-wide text-muted-foreground">{label}</span><button type="button" onClick={() => copy(String(value), label)} className="text-primary" aria-label={`Копіювати ${label}`}>{copied === label ? <Check className="size-4" /> : <Copy className="size-4" />}</button></div><p className="mt-2 break-words font-mono text-sm leading-6">{value}</p></div>)}</div><div className="mt-5 flex items-center justify-between rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm"><span className="text-muted-foreground">Реквізити активні ще</span><span className="font-mono font-semibold text-primary">{String(Math.floor(secondsLeft / 60)).padStart(2, "0")}:{String(secondsLeft % 60).padStart(2, "0")}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Після переказу натисніть кнопку нижче — заявка отримає статус «очікує перевірки».</p>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}<button type="button" onClick={confirm} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 font-medium text-primary-foreground">Я підтверджую оплату <Check className="size-4" /></button></div></motion.section>}
      {step === "sent" && <motion.section key="sent" initial={{ opacity: 0, scale: .98 }} animate={{ opacity: 1, scale: 1 }} className="mx-auto max-w-2xl text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check className="size-8" /></div><p className="mt-6 text-sm font-medium uppercase tracking-[.2em] text-primary">Заявку отримано</p><h1 className="mt-3 text-3xl font-semibold text-balance">Ваш донат обробляється</h1><p className="mx-auto mt-4 max-w-lg text-base leading-7 text-muted-foreground">Ми зафіксували повідомлення про переказ. Адміністратор перевірить його вручну та оновить статус транзакції.</p><div className="mx-auto mt-8 max-w-md rounded-2xl border border-foreground/10 bg-card p-5 text-left"><div className="flex justify-between gap-4 text-sm"><span className="text-muted-foreground">Номер заявки</span><button type="button" onClick={() => copy(reference, "reference")} className="flex items-center gap-2 font-mono text-primary">{reference}{copied === "reference" ? <Check className="size-4" /> : <Clipboard className="size-4" />}</button></div><div className="mt-3 flex justify-between gap-4 text-sm"><span className="text-muted-foreground">Статус</span><span className="font-medium">Очікує перевірки</span></div><div className="mt-3 flex justify-between gap-4 text-sm"><span className="text-muted-foreground">Реквізити активні до</span><span className="font-medium">{new Date(expiresAt).toLocaleString("uk-UA")}</span></div></div><button type="button" onClick={() => router.push("/")} className="mt-8 rounded-xl bg-primary px-5 py-3 font-medium text-primary-foreground">Повернутися на INPOM</button></motion.section>}
    </AnimatePresence>
  </div>
}
